// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloneAgent(arg1:string,arg2:Record<string, any>):Promise<main.Agent>;

export function CreateAgent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:Array<string>):Promise<main.Agent>;

export function DeleteAgent(arg1:string):Promise<void>;

export function GetAPIURL():Promise<string>;

export function GetAgent(arg1:string):Promise<main.Agent>;

export function GetTools():Promise<Array<main.Tool>>;

export function ListAgents():Promise<Array<main.Agent>>;

export function RunAgent(arg1:string,arg2:string,arg3:Record<string, any>):Promise<main.RunAgentResponse>;

export function SetAPIURL(arg1:string):Promise<string>;
