// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneAgent(arg1, arg2) {
  return window['go']['main']['App']['CloneAgent'](arg1, arg2);
}

export function CreateAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function RunAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunAgent'](arg1, arg2, arg3);
}

export function SetAPIURL(arg1) {
  return window['go']['main']['App']['SetAPIURL'](arg1);
}
